# Options Trading System Configuration

# Data paths
data:
  tick_data_path: "data/tick_data"
  candles_path: "data/candles"
  instruments_path: "data/instruments"

# Candle builder settings
candle_builder:
  timeframes: ["1s", "1m", "5m", "15m", "30m", "1h", "1d"]
  default_timeframe: "1m"

# Logging configuration
logging:
  level: "INFO"
  log_dir: "logs"
  max_file_size: 10485760  # 10MB
  backup_count: 5

# Trading settings
trading:
  max_positions: 10
  max_daily_loss: 10000
  default_lot_size: 1

# Strategy settings
strategy:
  supertrend:
    period: 10
    multiplier: 3.0
    enabled: true
  output_dir: "strategy_outputs"
  signal_confidence_threshold: 0.5

# Backtesting settings
backtesting:
  initial_capital: 100000
  commission: 0.001  # 0.1%
  slippage: 0.0005  # 0.05%
  start_date: "2024-01-01"
  end_date: "2024-12-31"

# Paper trading settings
paper_trading:
  initial_capital: 100000
  commission_rate: 0.001
  slippage_rate: 0.0005
  update_interval: 0.1  # seconds

# Risk management settings
risk_management:
  max_portfolio_loss_percent: 0.05  # 5%
  max_position_size_percent: 0.10   # 10%
  max_daily_trades: 50
  max_drawdown_percent: 0.10        # 10%
  stop_loss_percent: 0.05           # 5%
  take_profit_percent: 0.10         # 10%
  max_open_positions: 5

# Live trading settings
live_trading:
  enabled: false
  broker_api_key: "YOUR_API_KEY"
  broker_api_secret: "YOUR_API_SECRET"
  websocket_url: "wss://api.broker.com/ws"

# Broker settings
broker:
  kite_connect:
    api_key: "YOUR_KITE_API_KEY"
    api_secret: "YOUR_KITE_API_SECRET"
    access_token: "YOUR_KITE_ACCESS_TOKEN"
    user_id: "YOUR_KITE_USER_ID"
    password: "YOUR_KITE_PASSWORD"
    twofa: "YOUR_KITE_TWOFA"
    pin: "YOUR_KITE_PIN"
    redirect_url: "http://localhost:8000"
    debug: false
  default_product: "MIS"  # MIS, CNC, NRML
  default_variety: "regular"  # regular, bo, co, amo
  default_exchange: "NSE"

# Risk Management settings
risk_management:
  # Risk Engine Configuration
  risk_engine:
    max_portfolio_loss_percent: 0.05  # 5% max portfolio loss
    max_daily_loss_percent: 0.02      # 2% max daily loss
    max_drawdown_percent: 0.10        # 10% max drawdown
    max_position_size_percent: 0.10   # 10% max position size
    max_concentration_percent: 0.25   # 25% max concentration
    max_open_positions: 10            # Max 10 open positions
    max_daily_trades: 50              # Max 50 trades per day
    max_trades_per_hour: 10           # Max 10 trades per hour
    
  # Kill Switch Configuration
  kill_switch:
    enable_auto_close: true           # Auto-close positions on kill switch
    close_all_positions: true         # Close all positions
    cancel_pending_orders: true       # Cancel pending orders
    send_notifications: true          # Send notifications
    
  # Risk Monitor Configuration
  risk_monitor:
    update_interval: 1.0              # Update every 1 second
    alert_cooldown: 300.0             # 5 minute alert cooldown
    max_alerts_per_hour: 100          # Max 100 alerts per hour
    
  # Position Limits Configuration
  position_limits:
    max_position_size_percent: 0.10   # 10% max position size
    max_position_value: 50000.0       # ₹50,000 max position value
    max_position_quantity: 1000       # 1000 max quantity
    max_concentration_percent: 0.25   # 25% max concentration
    max_positions_per_symbol: 3       # Max 3 positions per symbol
    max_total_positions: 10           # Max 10 total positions
    
  # Margin Management Configuration
  margin_management:
    initial_margin_percent: 0.20      # 20% initial margin
    maintenance_margin_percent: 0.15  # 15% maintenance margin
    max_margin_utilization_percent: 0.80  # 80% max margin utilization
    warning_margin_percent: 0.70      # 70% warning margin level
    
  # Risk Alerts Configuration
  risk_alerts:
    enable_log_alerts: true           # Enable log-based alerts
    max_alerts_per_hour: 100          # Max 100 alerts per hour
    alert_cooldown_seconds: 300       # 5 minute cooldown between alerts
    
  # Risk Dashboard Configuration
  risk_dashboard:
    update_interval: 1.0              # Update every 1 second
    max_history_hours: 24             # Keep 24 hours of history
