# Options Trading System Configuration

# Data paths
data:
  tick_data_path: "data/tick_data"
  candles_path: "data/candles"
  instruments_path: "data/instruments"

# Candle builder settings
candle_builder:
  timeframes: ["1s", "1m", "5m", "15m", "30m", "1h", "1d"]
  default_timeframe: "1m"

# Logging configuration
logging:
  level: "INFO"
  log_dir: "logs"
  max_file_size: 10485760  # 10MB
  backup_count: 5

# Trading settings
trading:
  max_positions: 10
  max_daily_loss: 10000
  default_lot_size: 1

# Strategy settings
strategy:
  supertrend:
    period: 10
    multiplier: 3.0
    enabled: true
  output_dir: "strategy_outputs"
  signal_confidence_threshold: 0.5

# Backtesting settings
backtesting:
  initial_capital: 100000
  commission: 0.001  # 0.1%
  slippage: 0.0005  # 0.05%
  start_date: "2024-01-01"
  end_date: "2024-12-31"
